version: '3'
services:
  postgres:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'abcd1234'
      - POSTGRES_DB:'postgres'
    ports:
      - '5431:5432'
    networks:
      - main
networks:
  main:
    driver: bridge